_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.4
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
K:
    value: 1
batch_size:
    value: 128
beta:
    value: 2.5
cuda:
    value: false
datadir:
    value: ../data
epochs:
    value: 250
experiment:
    value: PolyMNIST_1
inception_path:
    value: ../data/pt_inception-2015-12-05-6726825d.pth
latent_dim_c:
    value: 40
latent_dim_w:
    value: 32
latent_dim_z:
    value: 32
learn_prior_c:
    value: true
llik_scaling:
    value: 0
no_cuda:
    value: false
obj:
    value: iwae
outputdir:
    value: ../outputs
pretrained_clfs_dir_path:
    value: ../data/trained_clfs_polyMNIST
print_freq:
    value: 50
priorposterior:
    value: Laplace
seed:
    value: 2
